esphome:
  name: "esphome-web-0e9986"

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "21TB9w5ZAWxO7H9NmqXwdmWJYaOEWfAxxxTyZXoUu+w="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
#  manual_ip:
#    static_ip: 192.168.1.33
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0
#    dns1: 192.168.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-0E9986"
    password: "xrqqqY2SyjK1"

captive_portal:

spi:
  clk_pin: D5
  mosi_pin: D7
  miso_pin: D6

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%

font:
  - file: "gfonts://Roboto"
    id: font1
    size: 20

display:
  - platform: ili9341
    model: "TFT_2.4"
    cs_pin: D2
    dc_pin: D4
    #led_pin: 3.3v
    reset_pin: D3
    rotation: 90
    id: tft_ha
    lambda: |-
      it.fill(Color::BLACK);
      it.print(0, 0, id(font1), id(my_red), TextAlign::TOP_LEFT, "Hello World!");
